# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Run home-page-redirect
        run: pm2 restart home-page-redirect || pm2 start ./ecosystem.config.js
